In [89]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LinearRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
pd.set_option('display.max_columns', 27)
arquivo = pd.read_csv('C:/Users/jose-/OneDrive/Área de Trabalho/Arquivos_para_manipulação_em_python/558648_1018837_bundle_archive/SBAnational.csv')
arquivo.head()

C:\Users\jose-\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,LoanNr_ChkDgt,Name,City,State,Zip,Bank,BankState,NAICS,ApprovalDate,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,RevLineCr,LowDoc,ChgOffDate,DisbursementDate,DisbursementGross,BalanceGross,MIS_Status,ChgOffPrinGr,GrAppv,SBA_Appv
0,1000014003,ABC HOBBYCRAFT,EVANSVILLE,IN,47711,FIFTH THIRD BANK,OH,451120,28-Feb-97,1997,84,4,2.0,0,0,1,0,N,Y,NaN,28-Feb-99,"$60,000.00",$0.00,P I F,$0.00,"$60,000.00","$48,000.00"
1,1000024006,LANDMARK BAR & GRILLE (THE),NEW PARIS,IN,46526,1ST SOURCE BANK,IN,722410,28-Feb-97,1997,60,2,2.0,0,0,1,0,N,Y,NaN,31-May-97,"$40,000.00",$0.00,P I F,$0.00,"$40,000.00","$32,000.00"
2,1000034009,"WHITLOCK DDS, TODD M.",BLOOMINGTON,IN,47401,GRANT COUNTY STATE BANK,IN,621210,28-Feb-97,1997,180,7,1.0,0,0,1,0,N,N,NaN,31-Dec-97,"$287,000.00",$0.00,P I F,$0.00,"$287,000.00","$215,250.00"
3,1000044001,"BIG BUCKS PAWN & JEWELRY, LLC",BROKEN ARROW,OK,74012,1ST NATL BK & TR CO OF BROKEN,OK,0,28-Feb-97,1997,60,2,1.0,0,0,1,0,N,Y,NaN,30-Jun-97,"$35,000.00",$0.00,P I F,$0.00,"$35,000.00","$28,000.00"
4,1000054004,"ANASTASIA CONFECTIONS, INC.",ORLANDO,FL,32801,FLORIDA BUS. DEVEL CORP,FL,0,28-Feb-97,1997,240,14,1.0,7,7,1,0,N,N,NaN,14-May-97,"$229,000.00",$0.00,P I F,$0.00,"$229,000.00","$229,000.00"

In [90]:
arquivo.drop('LoanNr_ChkDgt', axis=1, inplace=True)
arquivo.drop('Name', axis=1, inplace=True)
arquivo.drop('City', axis=1, inplace=True)
arquivo.drop('State', axis=1, inplace=True)
arquivo.drop('Zip', axis=1, inplace=True)
arquivo.drop('Bank', axis=1, inplace=True)

In [91]:
#definindo alvo
y = arquivo['SBA_Appv']
x = arquivo.drop('SBA_Appv',axis=1)

In [92]:
#Vendo quais dados estão faltantes 
faltantes = arquivo.isnull().sum()
faltantes_percentual = (faltantes / len(arquivo['UrbanRural']))*100
print(faltantes_percentual)

BankState             0.174162
NAICS                 0.000000
ApprovalDate          0.000000
ApprovalFY            0.000000
Term                  0.000000
NoEmp                 0.000000
NewExist              0.015125
CreateJob             0.000000
RetainedJob           0.000000
FranchiseCode         0.000000
UrbanRural            0.000000
RevLineCr             0.503579
LowDoc                0.287156
ChgOffDate           81.905526
DisbursementDate      0.263356
DisbursementGross     0.000000
BalanceGross          0.000000
MIS_Status            0.222095
ChgOffPrinGr          0.000000
GrAppv                0.000000
SBA_Appv              0.000000
dtype: float64

In [93]:
arquivo.drop('ChgOffDate', axis=1, inplace=True)

In [94]:
arquivo['SBA_Appv'] = arquivo['SBA_Appv'].str.replace("$","").str.replace(",","")
arquivo['DisbursementGross'] = arquivo['DisbursementGross'].str.replace("$","").str.replace(",","")
arquivo['BalanceGross'] = arquivo['BalanceGross'].str.replace("$","").str.replace(",","")
arquivo['ChgOffPrinGr'] = arquivo['ChgOffPrinGr'].str.replace("$","").str.replace(",","")
arquivo['GrAppv'] = arquivo['GrAppv'].str.replace("$","").str.replace(",","")
arquivo['RevLineCr'] = arquivo['RevLineCr'].replace("N",0).replace("Y",1)
arquivo['LowDoc'] = arquivo['LowDoc'].replace("N",0).replace("Y",1)

In [95]:
arquivo['SBA_Appv'] = arquivo['SBA_Appv'].astype(float)
arquivo['DisbursementGross'] = arquivo['DisbursementGross'].astype(float)
arquivo['BalanceGross'] = arquivo['BalanceGross'].astype(float)
arquivo['ChgOffPrinGr'] = arquivo['ChgOffPrinGr'].astype(float)
arquivo['GrAppv'] = arquivo['GrAppv'].astype(float)

In [96]:
from collections import Counter

Counter(arquivo['LowDoc'])

Counter({1: 110335,
         0: 782822,
         'C': 758,
         '1': 1,
         nan: 2582,
         'S': 603,
         'R': 75,
         'A': 497,
         '0': 1491})

In [97]:
arquivo['LowDoc'].replace("C",'',inplace=True)
arquivo['LowDoc'].replace("1","nan",inplace=True)
arquivo['LowDoc'].replace("S","nan",inplace=True)
arquivo['LowDoc'].replace("R","nan",inplace=True)
arquivo['LowDoc'].replace("A","nan",inplace=True)
arquivo['LowDoc'].replace("0","nan",inplace=True)

In [98]:
Counter(arquivo['LowDoc'])

Counter({1: 110335, 0: 782822, '': 758, 'nan': 2667, nan: 2582})

In [64]:
#Vendo quais dados estão faltantes 
faltantes = arquivo.isnull().sum()
faltantes_percentual = (faltantes / len(arquivo['UrbanRural']))*100
print(faltantes_percentual)

BankState            0.174162
NAICS                0.000000
ApprovalDate         0.000000
ApprovalFY           0.000000
Term                 0.000000
NoEmp                0.000000
NewExist             0.015125
CreateJob            0.000000
RetainedJob          0.000000
FranchiseCode        0.000000
UrbanRural           0.000000
RevLineCr            0.503579
LowDoc               0.287156
DisbursementDate     0.263356
DisbursementGross    0.000000
BalanceGross         0.000000
MIS_Status           0.222095
ChgOffPrinGr         0.000000
GrAppv               0.000000
SBA_Appv             0.000000
dtype: float64